name: Self-hosted Runner Workflow

on:
  push:
    branches:
      - test-2

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "gm"
