name: Secrets Example

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use secret in action
        run: echo "My secret key is ${{ secrets.KEER }}"

  deploy:
    runs-on: ubuntu-latest
    environment: testkeerthana

    steps:
      - name: Deploy to environment
        run: |
          echo "Deploying to ${{ github.environment }}"
          echo "${{ secrets.NAME }}"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: compare secrets
        run: |
          if [ "${{ secrets.KEER }}" == "${{ secrets.NAME }}" ]; then
            echo "The secrets KEER and NAME are the same."
          else
            echo "The secrets KEER and NAME are different."
          fi
